/**
 * Builds a regex that matches trace lines generated by a given trace function.
 * Matches both single-line calls like:
 *   crerror(...);
 *   console.log(...);
 *   print(...)
 */
export function buildTraceLineRegex(traceFunction: string): RegExp {
  const escaped = traceFunction.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  // Matches the full line (with optional leading whitespace) that contains a call to traceFunction
  return new RegExp(`^[^\\S\\n]*${escaped}\\s*\\(.*\\)\\s*;?\\s*$`);
}

/**
 * Returns true if a line looks like a trace line for any of the given functions.
 */
export function isTraceLine(line: string, traceFunctions: string[]): boolean {
  return traceFunctions.some((fn) => buildTraceLineRegex(fn).test(line));
}
